export const USER_REPOSITORY = 'USER_REPOSITORY';
export const USERSMSCODE_REPOSITORY = 'USERSMSCODE_REPOSITORY';

export const FORGET_PASSWORD_REPOSITORY = 'FORGET_PASSWORD_REPOSITORY';
export const USERPROFIE_REPOSITORY = 'USERPROFIE_REPOSITORY';
export const USER_PROFIE_VIEW_REPOSITORY = 'USER_PROFIE_VIEW_REPOSITORY';
export const SHOUTOUTS_REPOSITORY = 'SHOUTOUTS_REPOSITORY';
export const SHOUTOUTSTYPES_REPOSITORY = 'SHOUTOUTSTYPE_REPOSITORY';
export const POSTS_REPOSITORY = 'POSTS_REPOSITORY';
export const COMPANY_REPOSITORY = 'COMPANY_REPOSITORY';
export const COMMENTS_REPOSITORY = 'COMMENT_REPOSITORY';
export const REACTIONS_REPOSITORY = 'REACTIONS_REPOSITORY';
export const SHARES_REPOSITORY = 'SHARES_REPOSITORY';
export const JOBS_REPOSITORY = 'JOB_REPOSITORY';
export const MESSAGES_REPOSITORY = 'MESSAGES_REPOSITORY';
export const ROOM_REPOSITORY = 'ROOM_REPOSITORY';
export const NOTIFICATION_REPOSITORY = 'NOTIFICATION_REPOSITORY';
export const NOTIFICATION_PREFERENCE_REPOSITORY =
  'NOTIFICATION_PREFERENCE_REPOSITORY';
export const CONNECTION_REQUEST_REPOSITORY = 'CONNECTION_REQUEST_REPOSITORY';
